# -*- coding: utf-8 -*-

################################################################################
## Form generated from reading UI file 'main_pagesITuhwK.ui'
##
## Created by: Qt User Interface Compiler version 5.14.1
##
## WARNING! All changes made in this file will be lost when recompiling UI file!
################################################################################

from qt_core import *


class Ui_MainPages(object):
    def setupUi(self, MainPages):
        if MainPages.objectName():
            MainPages.setObjectName(u"MainPages")
        MainPages.resize(1195, 600)
        self.main_pages_layout = QVBoxLayout(MainPages)
        self.main_pages_layout.setSpacing(0)
        self.main_pages_layout.setObjectName(u"main_pages_layout")
        self.main_pages_layout.setContentsMargins(5, 5, 5, 5)
        self.pages = QStackedWidget(MainPages)
        self.pages.setObjectName(u"pages")
        self.pages.setStyleSheet(u"text-align: center;")
        self.teacher_home_page = QWidget()
        self.teacher_home_page.setObjectName(u"teacher_home_page")
        self.teacher_home_page.setStyleSheet(u"font-size: 14pt")
        self.tc_home_label = QLabel(self.teacher_home_page)
        self.tc_home_label.setObjectName(u"tc_home_label")
        self.tc_home_label.setGeometry(QRect(-4, -1, 1081, 141))
        font = QFont()
        self.tc_home_label.setFont(font)
        self.tc_home_label.setStyleSheet(u"font-size: 100px;")
        self.tc_home_label.setAlignment(Qt.AlignCenter)
        self.st_score = QLabel(self.teacher_home_page)
        self.st_score.setObjectName(u"st_score")
        self.st_score.setGeometry(QRect(0, 270, 531, 81))
        self.st_score.setFont(font)
        self.st_score.setStyleSheet(u"font-size: 50px;")
        self.st_score.setAlignment(Qt.AlignCenter)
        self.st_name = QLabel(self.teacher_home_page)
        self.st_name.setObjectName(u"st_name")
        self.st_name.setGeometry(QRect(0, 160, 531, 81))
        self.st_name.setFont(font)
        self.st_name.setStyleSheet(u"font-size: 50px;")
        self.st_name.setAlignment(Qt.AlignCenter)
        self.st_name_label = QLabel(self.teacher_home_page)
        self.st_name_label.setObjectName(u"st_name_label")
        self.st_name_label.setGeometry(QRect(550, 160, 531, 81))
        self.st_name_label.setFont(font)
        self.st_name_label.setStyleSheet(u"font-size: 50px;")
        self.st_name_label.setAlignment(Qt.AlignCenter)
        self.sc_1 = QRadioButton(self.teacher_home_page)
        self.sc_1.setObjectName(u"sc_1")
        self.sc_1.setGeometry(QRect(590, 290, 101, 41))
        self.sc_1.setStyleSheet(u"font-size: 40px;")
        self.sc_1.setIconSize(QSize(30, 30))
        self.sc_2 = QRadioButton(self.teacher_home_page)
        self.sc_2.setObjectName(u"sc_2")
        self.sc_2.setGeometry(QRect(690, 290, 101, 41))
        self.sc_2.setStyleSheet(u"font-size: 40px;")
        self.sc_2.setIconSize(QSize(30, 30))
        self.sc_3 = QRadioButton(self.teacher_home_page)
        self.sc_3.setObjectName(u"sc_3")
        self.sc_3.setGeometry(QRect(790, 290, 101, 41))
        self.sc_3.setStyleSheet(u"font-size: 40px;")
        self.sc_3.setIconSize(QSize(30, 30))
        self.sc_4 = QRadioButton(self.teacher_home_page)
        self.sc_4.setObjectName(u"sc_4")
        self.sc_4.setGeometry(QRect(890, 290, 101, 41))
        self.sc_4.setStyleSheet(u"font-size: 40px;")
        self.sc_4.setIconSize(QSize(30, 30))
        self.sc_5 = QRadioButton(self.teacher_home_page)
        self.sc_5.setObjectName(u"sc_5")
        self.sc_5.setGeometry(QRect(990, 290, 101, 41))
        self.sc_5.setStyleSheet(u"font-size: 40px;")
        self.sc_5.setIconSize(QSize(30, 30))
        self.start_class_frame = QFrame(self.teacher_home_page)
        self.start_class_frame.setObjectName(u"start_class_frame")
        self.start_class_frame.setGeometry(QRect(880, 470, 280, 80))
        self.start_class_frame.setMinimumSize(QSize(280, 80))
        self.start_class_frame.setMaximumSize(QSize(280, 80))
        self.start_class_frame.setFrameShape(QFrame.NoFrame)
        self.start_class_frame.setFrameShadow(QFrame.Raised)
        self.start_class_layout = QVBoxLayout(self.start_class_frame)
        self.start_class_layout.setSpacing(0)
        self.start_class_layout.setObjectName(u"start_class_layout")
        self.start_class_layout.setContentsMargins(0, 0, 0, 0)
        self.tc_select_class = QComboBox(self.teacher_home_page)
        self.tc_select_class.setObjectName(u"tc_select_class")
        self.tc_select_class.setGeometry(QRect(550, 490, 271, 51))
        self.tc_select_class.setStyleSheet(u"font-size: 35px;\n"
"background-color: rgb(27, 30, 35);\n"
"color: rgb(138, 149, 170);\n"
"text-align: center;")
        self.end_class_frame = QFrame(self.teacher_home_page)
        self.end_class_frame.setObjectName(u"end_class_frame")
        self.end_class_frame.setGeometry(QRect(40, 470, 280, 80))
        self.end_class_frame.setMinimumSize(QSize(280, 80))
        self.end_class_frame.setMaximumSize(QSize(280, 80))
        self.end_class_frame.setFrameShape(QFrame.NoFrame)
        self.end_class_frame.setFrameShadow(QFrame.Raised)
        self.end_class_layout = QVBoxLayout(self.end_class_frame)
        self.end_class_layout.setSpacing(0)
        self.end_class_layout.setObjectName(u"end_class_layout")
        self.end_class_layout.setContentsMargins(0, 0, 0, 0)
        self.pages.addWidget(self.teacher_home_page)
        self.page_2 = QWidget()
        self.page_2.setObjectName(u"page_2")
        self.label_2 = QLabel(self.page_2)
        self.label_2.setObjectName(u"label_2")
        self.label_2.setGeometry(QRect(290, 230, 271, 101))
        font1 = QFont()
        font1.setPointSize(14)
        self.label_2.setFont(font1)
        self.pages.addWidget(self.page_2)
        self.page_3 = QWidget()
        self.page_3.setObjectName(u"page_3")
        self.page_3.setStyleSheet(u"QFrame {\n"
"	font-size: 16pt;\n"
"}")
        self.label_3 = QLabel(self.page_3)
        self.label_3.setObjectName(u"label_3")
        self.label_3.setGeometry(QRect(250, 220, 381, 141))
        self.pages.addWidget(self.page_3)
        self.signup_page = QWidget()
        self.signup_page.setObjectName(u"signup_page")
        self.s_email_frame = QFrame(self.signup_page)
        self.s_email_frame.setObjectName(u"s_email_frame")
        self.s_email_frame.setGeometry(QRect(640, 270, 450, 80))
        self.s_email_frame.setMinimumSize(QSize(450, 80))
        self.s_email_frame.setMaximumSize(QSize(450, 80))
        self.s_email_frame.setStyleSheet(u"border-radius: 15")
        self.s_email_frame.setFrameShape(QFrame.NoFrame)
        self.s_email_frame.setFrameShadow(QFrame.Raised)
        self.s_email_layout = QVBoxLayout(self.s_email_frame)
        self.s_email_layout.setSpacing(0)
        self.s_email_layout.setObjectName(u"s_email_layout")
        self.s_email_layout.setContentsMargins(0, 0, 0, 0)
        self.s_pwd_frame = QFrame(self.signup_page)
        self.s_pwd_frame.setObjectName(u"s_pwd_frame")
        self.s_pwd_frame.setGeometry(QRect(640, 390, 450, 80))
        self.s_pwd_frame.setMinimumSize(QSize(450, 80))
        self.s_pwd_frame.setMaximumSize(QSize(450, 80))
        self.s_pwd_frame.setFrameShape(QFrame.NoFrame)
        self.s_pwd_frame.setFrameShadow(QFrame.Raised)
        self.s_pwd_layout = QVBoxLayout(self.s_pwd_frame)
        self.s_pwd_layout.setSpacing(0)
        self.s_pwd_layout.setObjectName(u"s_pwd_layout")
        self.s_pwd_layout.setContentsMargins(0, 0, 0, 0)
        self.s_email_label = QLabel(self.signup_page)
        self.s_email_label.setObjectName(u"s_email_label")
        self.s_email_label.setGeometry(QRect(0, 270, 641, 81))
        self.s_email_label.setFont(font)
        self.s_email_label.setStyleSheet(u"font-size: 50px;")
        self.s_email_label.setAlignment(Qt.AlignCenter)
        self.s_pwd_label = QLabel(self.signup_page)
        self.s_pwd_label.setObjectName(u"s_pwd_label")
        self.s_pwd_label.setGeometry(QRect(0, 390, 641, 81))
        self.s_pwd_label.setFont(font)
        self.s_pwd_label.setStyleSheet(u"font-size: 50px;\n"
"")
        self.s_pwd_label.setAlignment(Qt.AlignCenter)
        self.signup_label = QLabel(self.signup_page)
        self.signup_label.setObjectName(u"signup_label")
        self.signup_label.setGeometry(QRect(-4, -1, 1081, 141))
        self.signup_label.setFont(font)
        self.signup_label.setStyleSheet(u"font-size: 100px;")
        self.signup_label.setAlignment(Qt.AlignCenter)
        self.s_submit_frame = QFrame(self.signup_page)
        self.s_submit_frame.setObjectName(u"s_submit_frame")
        self.s_submit_frame.setGeometry(QRect(390, 490, 280, 80))
        self.s_submit_frame.setMinimumSize(QSize(280, 80))
        self.s_submit_frame.setMaximumSize(QSize(280, 80))
        self.s_submit_frame.setFrameShape(QFrame.StyledPanel)
        self.s_submit_frame.setFrameShadow(QFrame.Raised)
        self.s_submit_layout = QVBoxLayout(self.s_submit_frame)
        self.s_submit_layout.setSpacing(0)
        self.s_submit_layout.setObjectName(u"s_submit_layout")
        self.s_submit_layout.setContentsMargins(0, 0, 0, 0)
        self.s_user_type_label = QLabel(self.signup_page)
        self.s_user_type_label.setObjectName(u"s_user_type_label")
        self.s_user_type_label.setGeometry(QRect(0, 160, 641, 81))
        self.s_user_type_label.setFont(font)
        self.s_user_type_label.setStyleSheet(u"font-size: 50px;")
        self.s_user_type_label.setAlignment(Qt.AlignCenter)
        self.s_user_type = QComboBox(self.signup_page)
        self.s_user_type.addItem("")
        self.s_user_type.addItem("")
        self.s_user_type.setObjectName(u"s_user_type")
        self.s_user_type.setGeometry(QRect(710, 180, 311, 41))
        self.s_user_type.setStyleSheet(u"font-size: 35px;\n"
"background-color: rgb(27, 30, 35);\n"
"color: rgb(138, 149, 170);\n"
"text-align: center;")
        self.already_have_frame = QFrame(self.signup_page)
        self.already_have_frame.setObjectName(u"already_have_frame")
        self.already_have_frame.setGeometry(QRect(810, 50, 210, 60))
        self.already_have_frame.setMinimumSize(QSize(210, 60))
        self.already_have_frame.setMaximumSize(QSize(210, 60))
        self.already_have_frame.setFrameShape(QFrame.NoFrame)
        self.already_have_frame.setFrameShadow(QFrame.Raised)
        self.already_have_layout = QVBoxLayout(self.already_have_frame)
        self.already_have_layout.setSpacing(0)
        self.already_have_layout.setObjectName(u"already_have_layout")
        self.already_have_layout.setContentsMargins(0, 0, 0, 0)
        self.pages.addWidget(self.signup_page)
        self.signup_label.raise_()
        self.already_have_frame.raise_()
        self.s_email_frame.raise_()
        self.s_pwd_frame.raise_()
        self.s_email_label.raise_()
        self.s_pwd_label.raise_()
        self.s_submit_frame.raise_()
        self.s_user_type_label.raise_()
        self.s_user_type.raise_()
        self.login_page = QWidget()
        self.login_page.setObjectName(u"login_page")
        self.login_label = QLabel(self.login_page)
        self.login_label.setObjectName(u"login_label")
        self.login_label.setGeometry(QRect(-4, -1, 1081, 141))
        self.login_label.setFont(font)
        self.login_label.setStyleSheet(u"font-size: 100px;")
        self.login_label.setAlignment(Qt.AlignCenter)
        self.l_user_type = QComboBox(self.login_page)
        self.l_user_type.addItem("")
        self.l_user_type.addItem("")
        self.l_user_type.setObjectName(u"l_user_type")
        self.l_user_type.setGeometry(QRect(710, 180, 311, 41))
        self.l_user_type.setStyleSheet(u"font-size: 35px;\n"
"background-color: rgb(27, 30, 35);\n"
"color: rgb(138, 149, 170);\n"
"text-align: center;")
        self.l_pwd_frame = QFrame(self.login_page)
        self.l_pwd_frame.setObjectName(u"l_pwd_frame")
        self.l_pwd_frame.setGeometry(QRect(640, 390, 450, 80))
        self.l_pwd_frame.setMinimumSize(QSize(450, 80))
        self.l_pwd_frame.setMaximumSize(QSize(450, 80))
        self.l_pwd_frame.setFrameShape(QFrame.NoFrame)
        self.l_pwd_frame.setFrameShadow(QFrame.Raised)
        self.l_pwd_layout = QVBoxLayout(self.l_pwd_frame)
        self.l_pwd_layout.setSpacing(0)
        self.l_pwd_layout.setObjectName(u"l_pwd_layout")
        self.l_pwd_layout.setContentsMargins(0, 0, 0, 0)
        self.l_user_type_label = QLabel(self.login_page)
        self.l_user_type_label.setObjectName(u"l_user_type_label")
        self.l_user_type_label.setGeometry(QRect(0, 160, 641, 81))
        self.l_user_type_label.setFont(font)
        self.l_user_type_label.setStyleSheet(u"font-size: 50px;")
        self.l_user_type_label.setAlignment(Qt.AlignCenter)
        self.l_email_label_ = QLabel(self.login_page)
        self.l_email_label_.setObjectName(u"l_email_label_")
        self.l_email_label_.setGeometry(QRect(0, 270, 641, 81))
        self.l_email_label_.setFont(font)
        self.l_email_label_.setStyleSheet(u"font-size: 50px;")
        self.l_email_label_.setAlignment(Qt.AlignCenter)
        self.l_email_frame = QFrame(self.login_page)
        self.l_email_frame.setObjectName(u"l_email_frame")
        self.l_email_frame.setGeometry(QRect(640, 270, 450, 80))
        self.l_email_frame.setMinimumSize(QSize(450, 80))
        self.l_email_frame.setMaximumSize(QSize(450, 80))
        self.l_email_frame.setStyleSheet(u"border-radius: 15")
        self.l_email_frame.setFrameShape(QFrame.NoFrame)
        self.l_email_frame.setFrameShadow(QFrame.Raised)
        self.l_email_layout = QVBoxLayout(self.l_email_frame)
        self.l_email_layout.setSpacing(0)
        self.l_email_layout.setObjectName(u"l_email_layout")
        self.l_email_layout.setContentsMargins(0, 0, 0, 0)
        self.l_pwd_label = QLabel(self.login_page)
        self.l_pwd_label.setObjectName(u"l_pwd_label")
        self.l_pwd_label.setGeometry(QRect(0, 390, 641, 81))
        self.l_pwd_label.setFont(font)
        self.l_pwd_label.setStyleSheet(u"font-size: 50px;\n"
"")
        self.l_pwd_label.setAlignment(Qt.AlignCenter)
        self.dont_have_frame = QFrame(self.login_page)
        self.dont_have_frame.setObjectName(u"dont_have_frame")
        self.dont_have_frame.setGeometry(QRect(810, 50, 210, 60))
        self.dont_have_frame.setMinimumSize(QSize(210, 60))
        self.dont_have_frame.setMaximumSize(QSize(210, 60))
        self.dont_have_frame.setFrameShape(QFrame.NoFrame)
        self.dont_have_frame.setFrameShadow(QFrame.Raised)
        self.dont_have_layout = QVBoxLayout(self.dont_have_frame)
        self.dont_have_layout.setSpacing(0)
        self.dont_have_layout.setObjectName(u"dont_have_layout")
        self.dont_have_layout.setContentsMargins(0, 0, 0, 0)
        self.l_submit_frame = QFrame(self.login_page)
        self.l_submit_frame.setObjectName(u"l_submit_frame")
        self.l_submit_frame.setGeometry(QRect(390, 490, 280, 80))
        self.l_submit_frame.setMinimumSize(QSize(280, 80))
        self.l_submit_frame.setMaximumSize(QSize(280, 80))
        self.l_submit_frame.setFrameShape(QFrame.StyledPanel)
        self.l_submit_frame.setFrameShadow(QFrame.Raised)
        self.l_submit_layout = QVBoxLayout(self.l_submit_frame)
        self.l_submit_layout.setSpacing(0)
        self.l_submit_layout.setObjectName(u"l_submit_layout")
        self.l_submit_layout.setContentsMargins(0, 0, 0, 0)
        self.pages.addWidget(self.login_page)

        self.main_pages_layout.addWidget(self.pages)


        self.retranslateUi(MainPages)

        self.pages.setCurrentIndex(0)


        QMetaObject.connectSlotsByName(MainPages)
    # setupUi

    def retranslateUi(self, MainPages):
        MainPages.setWindowTitle(QCoreApplication.translate("MainPages", u"Form", None))
        self.tc_home_label.setText(QCoreApplication.translate("MainPages", u"Home", None))
        self.st_score.setText(QCoreApplication.translate("MainPages", u"Score: ", None))
        self.st_name.setText(QCoreApplication.translate("MainPages", u"Student Name: ", None))
        self.st_name_label.setText(QCoreApplication.translate("MainPages", u"[Start a class first]", None))
        self.sc_1.setText(QCoreApplication.translate("MainPages", u"1", None))
        self.sc_2.setText(QCoreApplication.translate("MainPages", u"2", None))
        self.sc_3.setText(QCoreApplication.translate("MainPages", u"3", None))
        self.sc_4.setText(QCoreApplication.translate("MainPages", u"4", None))
        self.sc_5.setText(QCoreApplication.translate("MainPages", u"5", None))
        self.label_2.setText(QCoreApplication.translate("MainPages", u"Page 2", None))
        self.label_3.setText(QCoreApplication.translate("MainPages", u"Page 3", None))
        self.s_email_label.setText(QCoreApplication.translate("MainPages", u"Email", None))
        self.s_pwd_label.setText(QCoreApplication.translate("MainPages", u"Password", None))
        self.signup_label.setText(QCoreApplication.translate("MainPages", u"Signup", None))
        self.s_user_type_label.setText(QCoreApplication.translate("MainPages", u"User Type", None))
        self.s_user_type.setItemText(0, QCoreApplication.translate("MainPages", u"Teacher", None))
        self.s_user_type.setItemText(1, QCoreApplication.translate("MainPages", u"Student", None))

        self.login_label.setText(QCoreApplication.translate("MainPages", u"Login", None))
        self.l_user_type.setItemText(0, QCoreApplication.translate("MainPages", u"Teacher", None))
        self.l_user_type.setItemText(1, QCoreApplication.translate("MainPages", u"Student", None))

        self.l_user_type_label.setText(QCoreApplication.translate("MainPages", u"User Type", None))
        self.l_email_label_.setText(QCoreApplication.translate("MainPages", u"Email", None))
        self.l_pwd_label.setText(QCoreApplication.translate("MainPages", u"Password", None))
    # retranslateUi

